# Generated by Django 3.1.1 on 2021-03-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_delete_profile'),
        ('users', '0002_auto_20210319_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(related_name='cart', to='web.Lot', verbose_name='Корзина'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite', to='web.Lot', verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='USERNAME', max_length=500, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(default='USERNAME', max_length=500, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='USERNAME', max_length=500, verbose_name='Фамилия'),
        ),
    ]
