# Generated by Django 3.1.1 on 2021-03-18 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория товаров')),
            ],
        ),
        migrations.CreateModel(
            name='Exporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название продавца')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес продавца')),
                ('tel', models.CharField(max_length=255, verbose_name='Телефон продавца')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('material', models.CharField(max_length=255, verbose_name='Материал товара')),
                ('purpose', models.CharField(max_length=255, verbose_name='Назначение товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Категория товара')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.exporter', verbose_name='Поставщик товара')),
            ],
        ),
    ]
