# Generated by Django 3.1.1 on 2021-03-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210317_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Категория товаров'),
        ),
        migrations.AlterField(
            model_name='exporter',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес продавца'),
        ),
        migrations.AlterField(
            model_name='exporter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название продавца'),
        ),
        migrations.AlterField(
            model_name='exporter',
            name='tel',
            field=models.CharField(max_length=255, verbose_name='Телефон продавца'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='material',
            field=models.CharField(max_length=255, verbose_name='Материал товара'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='purpose',
            field=models.CharField(max_length=255, verbose_name='Назначение товара'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='person_type',
            field=models.CharField(max_length=255, verbose_name='Лицо'),
        ),
    ]
