# Generated by Django 3.1.1 on 2021-03-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210317_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
